name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (if any)
        run: echo "No tests yet"
      - name: Build Docker image
        run: docker build -t container-backend .
      - name: Simulate Deploy
        run: bash run.sh & 